spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lc
    username: postgres
    password: 4999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

jwt:
  access:
    token:
      expiry: 3600000 # 60 minutes
      secret:
        key: E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key: