spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lc
    username: postgres
    password: 4999
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true