spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lc
    username: postgres
    password: 4999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10KB
      max-file-size: 100MB
      max-request-size: 150MB

jwt:
  access:
    token:
      expiry: 3600000 # 60 minutes
      secret:
        key: c67d1e7f9bbc0ed884c39caacb0b6f8f75aef72cf6de49476b4c0196ccdb41ff

  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key: